//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApiGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientApiGenerator.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Net.Http;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using Newtonsoft.Json;
        ///
        ///namespace Avalara.AvaTax.RestClient
        ///{
        ///    public partial class AvaTaxClient
        ///    {
        ///@@APILIST@@
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string api_class_template_csharp {
            get {
                return ResourceManager.GetString("api_class_template_csharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         /// &lt;summary&gt;
        ///        /// @@COMMENT@@
        ///        /// &lt;/summary&gt;
        ///@@PARAMCOMMENTS@@
        ///        public async Task&lt;@@TYPENAME@@&gt; @@APINAME@@(@@PARAMS@@)
        ///        {
        ///            var path = new AvaTaxPath(&quot;&quot;@@URI@@&quot;&quot;);@@PARAMBUILDER@@
        ///            return await RestCall&lt;@@TYPENAME@@&gt;(&quot;&quot;@@HTTPVERB@@&quot;&quot;, path, @@PAYLOAD@@);
        ///        }.
        /// </summary>
        internal static string api_template_csharp {
            get {
                return ResourceManager.GetString("api_template_csharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Net.Http;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using Newtonsoft.Json;
        ///
        ///namespace Avalara.AvaTax.RestClient
        ///{
        ///    /// &lt;summary&gt;
        ///    /// @@COMMENT@@
        ///    /// &lt;/summary&gt;
        ///    public class @@MODELCLASS@@
        ///    {
        ///@@PROPERTYLIST@@
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string model_class_template_csharp {
            get {
                return ResourceManager.GetString("model_class_template_csharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         /// &lt;summary&gt;
        ///        /// @@COMMENT@@
        ///        /// &lt;/summary&gt;
        ///        public @@PROPERTYTYPE@@ @@PROPERTYNAME@@ { get; set; }
        ///.
        /// </summary>
        internal static string model_property_template_csharp {
            get {
                return ResourceManager.GetString("model_property_template_csharp", resourceCulture);
            }
        }
    }
}
