/* 
 * AvaTax API
 *
 * REST interface to Avalara's enterprise tax service, AvaTax.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Avalara.AvaTax.RestClient.Model
{
    /// <summary>
    /// Settle this transaction with your ledger by verifying its amounts.              If the transaction is not yet committed, you may specify the \&quot;commit\&quot; value to commit it to the ledger and allow it to be reported.              You may also optionally change the transaction&#39;s code by specifying the \&quot;newTransactionCode\&quot; value.
    /// </summary>
    [DataContract]
    public partial class ChangeTransactionCodeModel :  IEquatable<ChangeTransactionCodeModel>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChangeTransactionCodeModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ChangeTransactionCodeModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ChangeTransactionCodeModel" /> class.
        /// </summary>
        /// <param name="NewCode">To change the transaction code for this transaction, specify the new transaction code here. (required).</param>
        public ChangeTransactionCodeModel(string NewCode = null)
        {
            // to ensure "NewCode" is required (not null)
            if (NewCode == null)
            {
                throw new InvalidDataException("NewCode is a required property for ChangeTransactionCodeModel and cannot be null");
            }
            else
            {
                this.NewCode = NewCode;
            }
        }
        
        /// <summary>
        /// To change the transaction code for this transaction, specify the new transaction code here.
        /// </summary>
        /// <value>To change the transaction code for this transaction, specify the new transaction code here.</value>
        [DataMember(Name="newCode", EmitDefaultValue=false)]
        public string NewCode { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ChangeTransactionCodeModel {\n");
            sb.Append("  NewCode: ").Append(NewCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ChangeTransactionCodeModel);
        }

        /// <summary>
        /// Returns true if ChangeTransactionCodeModel instances are equal
        /// </summary>
        /// <param name="other">Instance of ChangeTransactionCodeModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ChangeTransactionCodeModel other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.NewCode == other.NewCode ||
                    this.NewCode != null &&
                    this.NewCode.Equals(other.NewCode)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.NewCode != null)
                    hash = hash * 59 + this.NewCode.GetHashCode();
                return hash;
            }
        }
    }

}
